### ISSUE TITLE
Respawning players will overheat

### ISSUE THREAD

**Issue by kaylee-kiako** [WolfieWaffle/BedOfNails#2]
From my survival playthrough (and a death by fire) it came to my attention that temperature persists across death, which can result in multiple deaths until the player eventually cools down.

### Setup:
- Minecraft 1.18.2
- Forge 40.0.44
- Tough as Nails 1.18.2-7.0.0.69
- Bed of Nails 1.18.2-1.2

### Steps to Reproduce:
With the above setup, attempt to overheat via swimming in lava/armor/biome/time/etc. When the player respawns, they will continue to overheat.

### Notes:
From other tests, it appears that temperature does not persist with a default Tough as Nails installation (i.e., without Bed of Nails.)

**Comment by kaylee-kiako** [comment]
Upon further investigation, you respawn with a temperature of 100, which isn't carrying over, but you will continue to take damage from overheating.

This is the case no matter the form of death.

**Comment by WolfieWaffle** [comment]
hm, I might have forgotten to reset things on death properly. I will look into it.

**Comment by WolfieWaffle** [comment]
I found the source of the issue and tested a fix, will be in the next version
