### ISSUE TITLE
Cannot join server

### ISSUE THREAD

**Issue by LunarFactory** [WolfieWaffle/BedOfNails#4]
[latest.log](https://github.com/WolfieWaffle/BedOfNails/files/8746913/latest.log)

Idk why this problem happens, but on BON 1.6 for 1.18.2, it has some problem.

Forge 40.1.19

**Comment by MaxWasUnavailable** [comment]
Can confirm. Hosting a dedicated server with BoN results in players being unable to join.

They all receive the following error:

`cannot invoke "net.minecraft.resources.resourcelocation.tostring()" because "p_130086_" is null`

**Comment by WolfieWaffle** [comment]
im trying to solve it now, no idea what part of the code is even erroring there

**Comment by WolfieWaffle** [comment]
ok I think it should be fixed, uploading now

**Comment by MaxWasUnavailable** [comment]
Works! Though I can't seem to find the armor lining anymore?

**Comment by WolfieWaffle** [comment]
really? I tested it on the fixed version. what specifically is not working?

**Comment by MaxWasUnavailable** [comment]
Disregard that. I was stupid and didn't realise armour lining isn't a new item but rather leather/leaf.
