### ISSUE TITLE
Liner does not show up

### ISSUE THREAD

**Issue by MaxWasUnavailable** [WolfieWaffle/BedOfNails#5]
Version: BoN 1.6.2

Liner does not show up when searching for items in creative mode.

**Comment by MaxWasUnavailable** [comment]
Nevermind, I'm an idiot. The liner is using leather / grass / etc...

Any chance this can be documented somewhere? Just for future reference :')

**Comment by WolfieWaffle** [comment]
hm, I did put it in the changelog but I guess I can add it to the actual project page
